In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
class GeneticAlgorithm:
  def __init__(self, point_size, map_size, fitness_function, population_size, selection_ratio, mutation_possibility, mutation_ratio, max_iter, termination_value) -> None:
    if point_size < 1:
      raise ValueError("point_size must be at least 1")
    if map_size < 1:
      raise ValueError("map_size must be at least 1")
    if mutation_possibility < 0 or mutation_possibility > 1:
      raise ValueError("mutation_possibility must be between 0 and 1")
    if mutation_ratio < 0 or mutation_ratio > 1:
      raise ValueError("mutation_ratio must be between 0 and 1")
    if selection_ratio < 0 or selection_ratio > 1:
      raise ValueError("selection_ratio must be between 0 and 1")
    if population_size % 2 != 0:
      raise ValueError("population_size must be even")
    if population_size < 4:
      raise ValueError("population_size must be at least 4")
    if max_iter < 1:
      raise ValueError("max_iter must be at least 1")

    self.point_size = point_size
    self.map_size = map_size
    self.fitness_function = fitness_function
    self.population_size = population_size
    self.selection_amount = int(selection_ratio * population_size)
    self.mutation_possibility = mutation_possibility
    self.mutation_ratio = mutation_ratio
    self.max_iter = max_iter
    self.termination_value = termination_value

  def optimize(self):
    points = [np.random.random(size=self.point_size) * self.map_size for _ in range(self.population_size)]
    iter_count = 0

    best_point, best_score = None, np.inf

    while best_score >= self.termination_value and iter_count <= self.max_iter:
      points = sorted(points, key=lambda x: self.fitness_function(x))
      best_point = points[0]
      best_score = self.fitness_function(best_point)
      best_points = points[:self.selection_amount]

      new_kids = []
      for i in range(self.selection_amount):
          indices = np.random.choice(len(best_points), size=2, replace=False)
          p_a, p_b = best_points[indices[0]], best_points[indices[1]]

          new_kid = (p_a + p_b) / 2
          mutation = np.random.random() < self.mutation_possibility
          if mutation:
              new_kid[0] += np.random.uniform(-1,1) * self.mutation_ratio * self.map_size
              new_kid[1] += np.random.uniform(-1,1) * self.mutation_ratio * self.map_size
              new_kid[2] += np.random.uniform(-1,1) * self.mutation_ratio * self.map_size
          new_kids.append(new_kid)

      points = new_kids + best_points
      iter_count += 1

    return best_point, best_score, iter_count

In [20]:
target_point = (np.random.random(size=3) * 400).round(5)
target_point

array([239.93236,  21.36406, 310.42352])

In [23]:
model = GeneticAlgorithm(
    point_size = 3,
    map_size = 400,
    fitness_function = lambda x: np.linalg.norm(x - target_point),
    population_size = 50,
    selection_ratio = 0.5,
    mutation_possibility = 0.1,
    mutation_ratio = 0.1,
    max_iter = 100,
    termination_value = 1
)

In [24]:
best_point, best_score, last_iter = model.optimize()
print(f"Best point: {best_point}")
print(f"Best score: {best_score}")
print(f"Last iteration: {last_iter}")

[ 24.27694291 370.9458062   42.99201386]
[ 24.27694291 370.9458062   42.99201386]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   21.27612583 348.65346714]
[187.2806867   2